---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Regicide Ji.
--- DateTime: 2021/9/17 23:14
---

require("moduleMain")

moduleMain = {

    a = function()
        print("hello world")
        _G.math.abs(1)

        local grp



    end
}

