/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_core_graphics_GraphicsUnit */

#ifndef _Included_com_core_graphics_GraphicsUnit
#define _Included_com_core_graphics_GraphicsUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_core_graphics_GraphicsUnit
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_core_graphics_GraphicsUnit_start
  (JNIEnv *, jobject);

/*
 * Class:     com_core_graphics_GraphicsUnit
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_core_graphics_GraphicsUnit_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_core_graphics_GraphicsUnit
 * Method:    push
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_core_graphics_GraphicsUnit_push
  (JNIEnv *, jobject);

/*
 * Class:     com_core_graphics_GraphicsUnit
 * Method:    remove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_core_graphics_GraphicsUnit_remove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
