/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_framework_nebula_network_Connection */

#ifndef _Included_com_framework_nebula_network_Connection
#define _Included_com_framework_nebula_network_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_framework_nebula_network_Connection
 * Method:    sendString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_framework_nebula_network_Connection_sendString
  (JNIEnv *, jobject);

/*
 * Class:     com_framework_nebula_network_Connection
 * Method:    send
 * Signature: (Lcom/framework/nebula/network/Connection;)V
 */
JNIEXPORT void JNICALL Java_com_framework_nebula_network_Connection_send
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
