/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_core_graphics_Pipeline */

#ifndef _Included_com_core_graphics_Pipeline
#define _Included_com_core_graphics_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setShaders
 * Signature: (Ljava/util/ArrayList;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setShaders
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setVertexArray
 * Signature: (Lcom/core/graphics/VertexArray;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setVertexArray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setElementArrayBuffer
 * Signature: (Lcom/core/graphics/ElementArrayBuffer;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setElementArrayBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setTransformFeedback
 * Signature: (Lcom/core/graphics/TransformFeedback;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setTransformFeedback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    addUniformBuffers
 * Signature: (Ljava/util/ArrayList;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_addUniformBuffers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    addShaderStorageBuffers
 * Signature: (Ljava/util/ArrayList;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_addShaderStorageBuffers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    addAtomicCounterBuffers
 * Signature: (Ljava/util/ArrayList;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_addAtomicCounterBuffers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    addUniforms
 * Signature: (Ljava/util/ArrayList;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_addUniforms
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    addTextures
 * Signature: ()Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_addTextures
  (JNIEnv *, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setFramebuffer
 * Signature: ()Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setFramebuffer__
  (JNIEnv *, jobject);

/*
 * Class:     com_core_graphics_Pipeline
 * Method:    setFramebuffer
 * Signature: (Lcom/core/graphics/Framebuffer;)Lcom/core/graphics/Pipeline;
 */
JNIEXPORT jobject JNICALL Java_com_core_graphics_Pipeline_setFramebuffer__Lcom_core_graphics_Framebuffer_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
